# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: figures.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'figures.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfigures.proto\x12\x07\x66igures\"\x1a\n\nGetRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"+\n\x0bGetResponse\x12\x0c\n\x04\x62ody\x18\x01 \x01(\x0c\x12\x0e\n\x06status\x18\x02 \x01(\x05\")\n\x0bPostRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\",\n\x0cPostResponse\x12\x0c\n\x04\x62ody\x18\x01 \x01(\x0c\x12\x0e\n\x06status\x18\x02 \x01(\x05\";\n\rStreamRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\x12\x0e\n\x06method\x18\x03 \x01(\t\"\x15\n\x05\x43hunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xa4\x01\n\x07\x46igures\x12\x30\n\x03Get\x12\x13.figures.GetRequest\x1a\x14.figures.GetResponse\x12\x33\n\x04Post\x12\x14.figures.PostRequest\x1a\x15.figures.PostResponse\x12\x32\n\x06Stream\x12\x16.figures.StreamRequest\x1a\x0e.figures.Chunk0\x01\x42\x1fZ\x1dtoronto-census/internal/figpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'figures_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035toronto-census/internal/figpb'
  _globals['_GETREQUEST']._serialized_start=26
  _globals['_GETREQUEST']._serialized_end=52
  _globals['_GETRESPONSE']._serialized_start=54
  _globals['_GETRESPONSE']._serialized_end=97
  _globals['_POSTREQUEST']._serialized_start=99
  _globals['_POSTREQUEST']._serialized_end=140
  _globals['_POSTRESPONSE']._serialized_start=142
  _globals['_POSTRESPONSE']._serialized_end=186
  _globals['_STREAMREQUEST']._serialized_start=188
  _globals['_STREAMREQUEST']._serialized_end=247
  _globals['_CHUNK']._serialized_start=249
  _globals['_CHUNK']._serialized_end=270
  _globals['_FIGURES']._serialized_start=273
  _globals['_FIGURES']._serialized_end=437
# @@protoc_insertion_point(module_scope)
