// proto/figures.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/figures.proto

package figpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_figures_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_figures_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_figures_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_figures_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_figures_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_figures_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GetResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	mi := &file_proto_figures_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_figures_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_proto_figures_proto_rawDescGZIP(), []int{2}
}

func (x *PostRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PostRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type PostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	mi := &file_proto_figures_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_figures_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_proto_figures_proto_rawDescGZIP(), []int{3}
}

func (x *PostResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PostResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_figures_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_figures_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_figures_proto_rawDescGZIP(), []int{4}
}

func (x *StreamRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StreamRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *StreamRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_proto_figures_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_figures_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_proto_figures_proto_rawDescGZIP(), []int{5}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_figures_proto protoreflect.FileDescriptor

const file_proto_figures_proto_rawDesc = "" +
	"\n" +
	"\x13proto/figures.proto\x12\afigures\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"9\n" +
	"\vGetResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"5\n" +
	"\vPostRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\":\n" +
	"\fPostResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"O\n" +
	"\rStreamRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\"\x1b\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xa4\x01\n" +
	"\aFigures\x120\n" +
	"\x03Get\x12\x13.figures.GetRequest\x1a\x14.figures.GetResponse\x123\n" +
	"\x04Post\x12\x14.figures.PostRequest\x1a\x15.figures.PostResponse\x122\n" +
	"\x06Stream\x12\x16.figures.StreamRequest\x1a\x0e.figures.Chunk0\x01B\x1fZ\x1dtoronto-census/internal/figpbb\x06proto3"

var (
	file_proto_figures_proto_rawDescOnce sync.Once
	file_proto_figures_proto_rawDescData []byte
)

func file_proto_figures_proto_rawDescGZIP() []byte {
	file_proto_figures_proto_rawDescOnce.Do(func() {
		file_proto_figures_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_figures_proto_rawDesc), len(file_proto_figures_proto_rawDesc)))
	})
	return file_proto_figures_proto_rawDescData
}

var file_proto_figures_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_figures_proto_goTypes = []any{
	(*GetRequest)(nil),    // 0: figures.GetRequest
	(*GetResponse)(nil),   // 1: figures.GetResponse
	(*PostRequest)(nil),   // 2: figures.PostRequest
	(*PostResponse)(nil),  // 3: figures.PostResponse
	(*StreamRequest)(nil), // 4: figures.StreamRequest
	(*Chunk)(nil),         // 5: figures.Chunk
}
var file_proto_figures_proto_depIdxs = []int32{
	0, // 0: figures.Figures.Get:input_type -> figures.GetRequest
	2, // 1: figures.Figures.Post:input_type -> figures.PostRequest
	4, // 2: figures.Figures.Stream:input_type -> figures.StreamRequest
	1, // 3: figures.Figures.Get:output_type -> figures.GetResponse
	3, // 4: figures.Figures.Post:output_type -> figures.PostResponse
	5, // 5: figures.Figures.Stream:output_type -> figures.Chunk
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_figures_proto_init() }
func file_proto_figures_proto_init() {
	if File_proto_figures_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_figures_proto_rawDesc), len(file_proto_figures_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_figures_proto_goTypes,
		DependencyIndexes: file_proto_figures_proto_depIdxs,
		MessageInfos:      file_proto_figures_proto_msgTypes,
	}.Build()
	File_proto_figures_proto = out.File
	file_proto_figures_proto_goTypes = nil
	file_proto_figures_proto_depIdxs = nil
}
