// proto/figures.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/figures.proto

package figpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Figures_Get_FullMethodName    = "/figures.Figures/Get"
	Figures_Post_FullMethodName   = "/figures.Figures/Post"
	Figures_Stream_FullMethodName = "/figures.Figures/Stream"
)

// FiguresClient is the client API for Figures service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FiguresClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error)
}

type figuresClient struct {
	cc grpc.ClientConnInterface
}

func NewFiguresClient(cc grpc.ClientConnInterface) FiguresClient {
	return &figuresClient{cc}
}

func (c *figuresClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Figures_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *figuresClient) Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, Figures_Post_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *figuresClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Figures_ServiceDesc.Streams[0], Figures_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, Chunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Figures_StreamClient = grpc.ServerStreamingClient[Chunk]

// FiguresServer is the server API for Figures service.
// All implementations must embed UnimplementedFiguresServer
// for forward compatibility.
type FiguresServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Post(context.Context, *PostRequest) (*PostResponse, error)
	Stream(*StreamRequest, grpc.ServerStreamingServer[Chunk]) error
	mustEmbedUnimplementedFiguresServer()
}

// UnimplementedFiguresServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFiguresServer struct{}

func (UnimplementedFiguresServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedFiguresServer) Post(context.Context, *PostRequest) (*PostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedFiguresServer) Stream(*StreamRequest, grpc.ServerStreamingServer[Chunk]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedFiguresServer) mustEmbedUnimplementedFiguresServer() {}
func (UnimplementedFiguresServer) testEmbeddedByValue()                 {}

// UnsafeFiguresServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FiguresServer will
// result in compilation errors.
type UnsafeFiguresServer interface {
	mustEmbedUnimplementedFiguresServer()
}

func RegisterFiguresServer(s grpc.ServiceRegistrar, srv FiguresServer) {
	// If the following call panics, it indicates UnimplementedFiguresServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Figures_ServiceDesc, srv)
}

func _Figures_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiguresServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Figures_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiguresServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Figures_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FiguresServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Figures_Post_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FiguresServer).Post(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Figures_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FiguresServer).Stream(m, &grpc.GenericServerStream[StreamRequest, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Figures_StreamServer = grpc.ServerStreamingServer[Chunk]

// Figures_ServiceDesc is the grpc.ServiceDesc for Figures service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Figures_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "figures.Figures",
	HandlerType: (*FiguresServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Figures_Get_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _Figures_Post_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Figures_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/figures.proto",
}
